### ISSUE TITLE
Error whenever I update Craft plugins

### ISSUE THREAD

**Issue by stevehurst** [miranj/craft-obfuscator#2]
I get an error from the Obfuscator plugin whenever I update any plugin in Craft. I'm running Craft 3.1.12 and Obfuscator 1.0.2.

```LogicException: Unable to register extension "miranj\obfuscator\twigextensions\ObfuscatorTwigExtension" as extensions have already been initialized. in /Users/stevehurst/Sites/kalypso.craft.local/vendor/twig/twig/lib/Twig/ExtensionSet.php:156
Stack trace:
#0 /Users/stevehurst/Sites/kalypso.craft.local/vendor/twig/twig/lib/Twig/Environment.php(672): Twig_ExtensionSet->addExtension(Object(miranj\obfuscator\twigextensions\ObfuscatorTwigExtension))
#1 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/web/View.php(299): Twig_Environment->addExtension(Object(miranj\obfuscator\twigextensions\ObfuscatorTwigExtension))
#2 /Users/stevehurst/Sites/kalypso.craft.local/vendor/miranj/craft-obfuscator/src/Obfuscator.php(32): craft\web\View->registerTwigExtension(Object(miranj\obfuscator\twigextensions\ObfuscatorTwigExtension))
#3 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/base/BaseObject.php(109): miranj\obfuscator\Obfuscator->init()
#4 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#5 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/base/Plugin.php(127): yii\base\Module->__construct('obfuscator', Object(craft\web\Application), Array)
#6 [internal function]: craft\base\Plugin->__construct('obfuscator', Object(craft\web\Application), Array)
#7 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#8 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('miranj\\obfuscat...', Array, Array)
#9 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('miranj\\obfuscat...', Array, Array)
#10 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#11 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('obfuscator', Array)
#12 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/base/ApplicationTrait.php(1223): craft\services\Plugins->loadPlugins()
#13 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->_postInit()
#14 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#15 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#16 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
#17 [internal function]: craft\web\Application->__construct(Array)
#18 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#19 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#20 /Users/stevehurst/Sites/kalypso.craft.local/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#21 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/bootstrap/bootstrap.php(255): yii\BaseYii::createObject(Array)
#22 /Users/stevehurst/Sites/kalypso.craft.local/vendor/craftcms/cms/bootstrap/web.php(42): require('/Users/stevehur...')
#23 /Users/stevehurst/Sites/kalypso.craft.local/public/index.php(20): require('/Users/stevehur...')
#24 {main}```

**Comment by rungta** [comment]
Thank you for reporting. Can you help us debug it by sharing some more details, like was is the exact exception thrown? Do you have any suspicion about the cause?

**Comment by stevehurst** [comment]
I've attached the error page. I'm not sure how to diagnose further. This is the error message:

> Unable to register extension "miranj\obfuscator\twigextensions\ObfuscatorTwigExtension" as extensions have already been initialized.

It looks like it's trying to register itself twice?

[LogicException.html.zip](https://github.com/miranj/craft-obfuscator/files/2895797/LogicException.html.zip)

**Comment by rungta** [comment]
Hmm. Can you try re-installing the plugin by:
1. Running `compose remove miranj/craft-obfuscator`
2. Deleting the entry for Obfuscator from your plugins table (if present) by running the following command: `DELETE FROM plugins WHERE plugins.handle = 'obfuscator'`
3. Check everything is working normally in your Craft install without the Obfuscator plugin
4. Download the plugin again `compose require miranj/craft-obfuscator`
5. Install `./craft install/plugin obfuscator`

Does that fix it?

**Comment by rungta** [comment]
Closing this issue as stale.
